test(ldapapi): [#63154] attempt to remove flakiness from test
This commit changes the "connection is down" part of the
`test_convert_ldap_uuids_to_dns` test within
`test_convert_ldap_uuids_to_dns.py`, as it is currently very flaky and
fails frequently with:
```
ldap3.core.exceptions.LDAPSocketOpenError: unable to send message, socket is not open
```
During the clean-up after the test has finished running, specifically
within the `purge_ldap` fixture.

The test has been made worse in that it no longer actually emulates a
connection failure on the socket level, but rather just replaces the
`ldap_connection` object with a mock, however the test should now no
longer be flaky, which is deemed a reasonable trade-off.