refactor(graphql): [#67163] make `actor_object` on `RegistrationBase` lazy
Required to break Strawberry issues:

strawberry.exceptions.unresolved_field_type.UnresolvedFieldTypeError: Could not resolve the type of 'address_type_response'. Check that the class is accessible from the global module scope.